# logging.yaml
version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"

handlers:
  console:
    class: "rich.logging.RichHandler"
    level: INFO
    # No show_time, markup, etc. here
    # 'formatter' is optional. You can omit it to use Rich's default console style.
  rotating_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: pyonhm.log
    maxBytes: 10485760  # 10MB
    backupCount: 5

loggers:
  pyonhm:
    handlers: [console, rotating_file]
    level: INFO
    propagate: no

root:
  handlers: [console, rotating_file]
  level: INFO
